server:
  port: 8081
  servlet:
    context-path: /client1
security:
  oauth2:
    client:
      clientId: xsy1
      clientSecret: xsy1
      user-authorization-uri: http://127.0.0.1:9999/server/oauth/authorize
      access-token-uri: http://127.0.0.1:9999/server/oauth/token
    resource:
      jwt:
        key-uri: http://127.0.0.1:9999/server/oauth/token_key

